### ISSUE TITLE
Scrape and store article content from URLs

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#1]
The *master input*, *extended* and *training* datasets all contain URLs. For initial exploration and later analysis, it would be nice to build functionality to scrape, strip, and store the article information.

**Comment by simonb83** [comment]
I'm starting to have a think about this one. I'll let you know when I have a rough outline of how I think this could work.

**Comment by georgerichardson** [comment]
Update: a `scraper` branch has been started with a new file `scraper.py` based on the `newspaper` module.
