### ISSUE TITLE
Scraper - Parsing PDFs?

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#17]
Currently, `scraper.py` only scrapes html pages. Can we also scrape and parse PDFs?

**Comment by coldfashioned** [comment]
Just saw this on the way to dinner. I've built a program for work to parse pdf's. so I was planning to incorporate that into the scraper. The trouble with pdfs is that they vary in quality, and sometimes don't give you much.

**Comment by jlln** [comment]
Great! I was expecting this to be a real pain so I'm glad you have something.

**Comment by georgerichardson** [comment]
That's great! A lot of these are "official" reports so maybe we'll be lucky with the quality. Even if we can get a fraction of them, that's a massive step.

**Comment by coldfashioned** [comment]
Cool - I'll work on this in the morning. I'll test stuff out and let you know what I come up with either on here or slack. I think pdfs made more recently are constructed better, and can be parsed using PyPDF2. I'll have figure out how to download / extract the pdf file, and then I think I can work with them. Hope I can help!

**Comment by jlln** [comment]
Nice work with the parser. I have looked into incorporating it into the scraper but I have encountered the issue of identifying PDFs:
- How to distinguish an url returning a pdf versus one returning html? 
	-The url is not sufficient to identify the return object type. 
	-I have tried using the python requests module to pull the header and examine the header content type. However this doesn't always work, because some urls return an html page that contains a pdf in an iframe. eg http://erccportal.jrc.ec.europa.eu/getdailymap/docId/1125

**Comment by coldfashioned** [comment]
Thanks! 

Good point. I didn't think about that case. I'm not sure if I know how to solve that at this point. I'll try to set aside some time to look into that later today / tomorrow.

**Comment by jlln** [comment]
I'm stumped too. I'll ask around today and let you know if I find anything. The task must be possible, because google chrome automatically renders the page as  a pdf.

**Comment by coldfashioned** [comment]
I haven't been available since the weekend, so I'm catching up with this now. On branch master, I don't see the code that I wrote for scraping pdfs, and when I try to switch to the scraper branch, I get a 404 error. Let me know what needs to be added to the pdf scraper and I'll get to work on it.

**Comment by georgerichardson** [comment]
Going to refactor this in now.
