### ISSUE TITLE
Explore refugee data in Jupyter Notebooks

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#18]
We want people to play around with our tool and do some data analysis and visualisations. Start a notebook, see what you can make or break and let us know below.

**Comment by georgerichardson** [comment]
Thanks for the latest addition @wwymak!

**Comment by ottoman91** [comment]
hi! id like to work on this issue. im currently working in the ICT4D space in west africa, and passionate about using data science/machine learning to solve problems in the development sector.

**Comment by georgerichardson** [comment]
@ottoman91 Cool! We have a Data for Democracy Slack channel where we're chatting about the project as a whole

**Comment by ottoman91** [comment]
yes, ive joined that group. will be reading the project documentation tonight and then get started on this.
