### ISSUE TITLE
Pipeline - save data to csv

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#19]
The scraper puts out a list of dictionaries with the contents and metadata from a webpage. We need to be able to save this as a csv. Bonus points if you can append it back to the original csv.

**Comment by georgerichardson** [comment]
I really like what @jlln has done with creating the SQLArticleInterface. At first I thought we should have a CSVArticleInterface too, but on reflection, perhaps we should default to putting data into a sqlite database, and then build in some helper functions that can take it and export to csv if the user might want to do that at any point. Any thoughts? Trying to imaging what might be useful for the analyst in the end.

**Comment by simonb83** [comment]
Hmmm...I tend to agree about storing everything in database as default, and then providing options for extracting, manipulating and saving data as needed.
Ultimately I think it gives more flexibility, as its easier to let an analyst play around using the tool and then export as and when they need when they are happy.

**Comment by jlln** [comment]
Yep that all sounds good to me.

**Comment by georgerichardson** [comment]
Ok. In that case I'll just make a helper function to do that, but the pipeline will revolve around getting articles into sql

**Comment by georgerichardson** [comment]
#49
