### ISSUE TITLE
Scraper - Tag broken URLs

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#2]
Lots of the URLs are broken, or contain information that can't be parsed as text (eg. videos, images). How can we filter them out and tag them as such.

**Comment by coldfashioned** [comment]
I noticed this as well. For the time being, I ended up ignoring them using a try / except looking for error 404's.

**Comment by georgerichardson** [comment]
Changing this to just focus on broken URLs. Made another issue for irrelevant content types.

**Comment by simonb83** [comment]
Closing for the time being with PRs #22 and #30
