### ISSUE TITLE
Pipeline - consistent date and time

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#20]
Haven't looked too deeply into `newspaper`'s handling of datetimes but if they vary from site to site, we will need to make them consistent. Maybe even having comma separated values for date, month and year published.

**Comment by simonb83** [comment]
Do we need to worry about timezone at all? I know that we'll have country code, but just wondering if also need to store this for datetime fields?

**Comment by georgerichardson** [comment]
I was working on the assumption that published date time is local but I guess that may not be true. I guess it depends whether we care about propagation of reports across news sources or linking them with social media.

**Comment by jlln** [comment]
The newspaper module returns datetimes as datetime.datetime objects, which are consistent, and have optional timezone information. So the cases we need to deal with are those where newspaper fails to extract a datetime but successfully extracts text and other information.

**Comment by georgerichardson** [comment]
Ok. I'm going to sort the timezone issue (I think converting to GMT is probably best) and also going to see if I can find a few examples of newspaper not working and rectify that.

**Comment by jlln** [comment]
I've just had a look at the newspaper source code to see how it extracts dates. You can see their code here:
https://github.com/codelucas/newspaper/blob/master/newspaper/extractors.py#L173

Might help you understand what weaknesses (if any) it has.

**Comment by georgerichardson** [comment]
Closing for now as newspaper tackles this fairly well and timezone information is rarely present on articles.
