### ISSUE TITLE
Best NLP approach to extract useful info from articles

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#3]
From the articles, we need to extract the whether individuals or households are being displaced (the reporting unit), how many of them, the date the article was published published and which reporting term is most appropriate.

**Comment by kmariano** [comment]
There are a few natural language libraries that will be able to do classification so we can identify subjects, key words, synonyms etc. One example is natural.js for node. I'm sure there is a python counterpart that could be used.

**Comment by wwymak** [comment]
I think apparently spacy (in python) is pretty decent in POS tagging and entity extraction?

**Comment by simonb83** [comment]
@wwymak  I've used nltk a couple of times in the past, but spacy looks really interesting and definitely worth checking out.
This comparison page is pretty interesting (admittedly not independent testing):
https://spacy.io/docs/api/

Probably the one place it might be lacking is in the multi-lingual support, but not even sure how relevant that might be yet.

**Comment by georgerichardson** [comment]
Thanks for the input all. I'd quite like to have a go at this, as I haven't used these packages before. If anyone wants to help out, that'd be welcome.

Spacy looks cool!

**Comment by wwymak** [comment]
@georgerichardson do you have the articles texts somewhere? I would be quite interested in having a go at them on the side this weekend while I am trying out similarity nlp stuff for twitter? (but I can't promise on any sort of success 😉)

**Comment by georgerichardson** [comment]
@wwymak that's half the challenge. Right now we don't actually have any article text. We have people working on scraping that. That's why I just started this issue to initiate a conversation about approaches. I'll let you know if we have anything to work with.

**Comment by simonb83** [comment]
Hey @wwymak, I just downloaded the contents of about 300 articles for people to play with for getting started on things like NLP, fact extraction etc. It's on [Dropbox](https://www.dropbox.com/sh/59lyts9d4ar1jcc/AADMyxDSQC_NGbpaPiuDGJ2ha?dl=0&preview=training_dataset_article_contents.csv) currently.
Unfortunately something seemed to happen to the text encoding on uploading to Dropbox, but if you want I can pass you my original data file.

**Comment by wwymak** [comment]
hi @simonb83 if you can pass me the original file that would be great :)

**Comment by simonb83** [comment]
Sure thing @wwymak. Here it is: https://s3-us-west-1.amazonaws.com/simon.bedford/d4d/article_contents.csv.gz

**Comment by simonb83** [comment]
@wwymak I was playing around with this this morning and it threw some errors....you may have better luck with this one: https://s3-us-west-1.amazonaws.com/simon.bedford/d4d/article_contents.csv

**Comment by georgerichardson** [comment]
Seems like we've settled on spaCy for now
