### ISSUE TITLE
Pull data from S3 bucket

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#4]
Currently, the csv data files are stored in my personal S3. We need to be able to download them locally or load them directly into a dataframe.

**Comment by mhoover** [comment]
@georgerichardson I'm happy to jump on this; can put some time in on evenings over the next couple of days. I'm on the D4D Slack at `mhoover` if you want to chat some more. I assume some access/permissions will be needed.

**Comment by georgerichardson** [comment]
@mhoover Cool! Pinging you on slack as this could need a bit of back and forth.

**Comment by georgerichardson** [comment]
Just for everyone's information, this one is on hold for a bit until we get the scraper closer to being finalised.

**Comment by Guilhermeslucas** [comment]
Want some help? I'm interested on working on it!

**Comment by simonb83** [comment]
@Guilhermeslucas We had this on hold for a bit, but...@georgerichardson wow that we have the scraper implemented, might be good to pick this up again?

**Comment by Guilhermeslucas** [comment]
This looks like a nice place to begin. Let me know if I can do something, I'd be really happy to help.

**Comment by georgerichardson** [comment]
@Guilhermeslucas We'd definitely still like to do this in two capacities. 
1) It would be useful just for development for us to be able to push and pull data from a bucket
2) As the code we've written turns into an app, this might be the way we choose to manage the data.

I would say you can safely get on with 1, but join the slack channel to discuss 2 with the front end/app folk to understand how we're going to manage data handling.

**Comment by mhoover** [comment]
@Guilhermeslucas @georgerichardson I'm tied up with other things, so I won't be able to help out in the near term. Awesome there will be some movement here.

**Comment by Guilhermeslucas** [comment]
Awesome guys! Thanks a lot! I want to ask a few questions about it. Its better to ask it here or on slack?

**Comment by simonb83** [comment]
@Guilhermeslucas so far we have been doing both GitHub comments + slack discussion.

I think for general questions and discussion slack is fine, however it is also sometimes easy to lose track of specific questions and also messages get deleted after a while, so if you have more specific / technical / code questions or comments then I think here would be better.

**Comment by Guilhermeslucas** [comment]
So, first, this part of the project should be a separated script or part of one that already exists?
What about permissions? To access S3, the user must have password, doesn't it?
The script must only push and pull all the dataset or I must write something that allows the user to do these actions with certains files?

Thanks a lot!

**Comment by georgerichardson** [comment]
@Guilhermeslucas this would be really useful for helping during development. I'm not sure right now if we'll need this functionality in the final application. Would love you to join the Slack discussion to help figure that out

**Comment by georgerichardson** [comment]
Going to close this issue until we have a better idea of what data storage we'll be using in the future.
