### ISSUE TITLE
Improve text extraction from URLs with beautifulsoup

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#5]
There is a barebones function to extract text from the URLs. However, this hasn't been tested across many different URLs and does not necessarily do the best job of extracting the main body of relevant text.

**Comment by coldfashioned** [comment]
George - Do you have a small sample subset of these URLs to use when building this function / script?

**Comment by georgerichardson** [comment]
Not a prebuilt one. Maybe use the `training_dataset.csv`?

**Comment by coldfashioned** [comment]
Ok - now I'm a bit confused (and maybe in over my head). The scrape_artlces.py program just changed a ton and I'm not sure which function is the one I should be working on? Has this issue already been tackled? I'd love to help, but I also don't want to hold anything up, if there are folks who have more time / are better able to take on this task.

**Comment by georgerichardson** [comment]
@coldfashioned Just realised you were never in the #refugees Slack channel where the link to the datasets were (the link is in a pinned post). Invited you.

Help definitely still wanted. We just came up with a new skeleton outline and @jlln just improved the scraper a bit, but the enhancements are still really needed. We're going to move this aspect to another repo though.

**Comment by coldfashioned** [comment]
Oh man, I'm getting frustrated. I have an idea, but I can't get going because I get an error (that seems to be common). I can't seem to get past it, though. Anyone have any tips for this:
ModuleNotFoundError: No module named 'bs4'

I've tried just about everything I could find from google. I'm using Python3, anaconda, and I have the environment set up with all the requirements. Blarg!

**Comment by coldfashioned** [comment]
TIL: Use the correct shebang and all will be well. I had a generic shebang line, when I needed to have it point to the path of my conda environment. Man, I feel dumb and triumphant (for fixing it) at the same time. I'll work on the function this afternoon - for real, this time!

**Comment by georgerichardson** [comment]
Did you have any luck here in the end? I came across the `newspaper` module which seems to do this exact task. I've been testing it out and it seems good. Going to factor it into the scraper and test out.

**Comment by jlln** [comment]
Oh that newspaper module looks ideal. Great find!

**Comment by georgerichardson** [comment]
Pretty much does the whole job! Almost done with it

**Comment by georgerichardson** [comment]
Just pushed to `scraper.py`. It's pretty basic right now. Can only take a list of urls

**Comment by georgerichardson** [comment]
Closing this for now as mostly resolved. Probably opportunities for optimisations further down the line.

**Comment by coldfashioned** [comment]
Wow - you guys move quickly on a Friday night! I had to do some work around the house, and boom - issue closed. Glad you guys got it sorted out, sorry I didn't come through. I did learn quite a bit about the whole process though, so I'm glad I gave it a shot. I hope I can help with the pdf issue now. I'll jump over there now.

**Comment by georgerichardson** [comment]
Haha. That's ok. It's only because the module we found made it so easy. Learned a lot here too.
