### ISSUE TITLE
Enhance country detection in article content

### ISSUE THREAD

**Issue by simonb83** [Data4Democracy/internal-displacement#51]
Enhance the `country_code` function in `interpreter.py` in order to more reliably recognize countries.
For example it currently fails for 'the United States' vs 'United States'.

It would also be good to try and detect countries even though the name is not explicitly mentioned, i.e. from city names etc.

The Mordecai library may be an option, however it requires its own NLP parsing and I was wondering if there was a simpler way to do this without using two NLP libraries + trained models.

**Comment by naoyak** [comment]
[SpaCy's named entity recognizer](https://demos.explosion.ai/displacy-ent/?text=The%20Syria-based%20jihadist%20group%20al-Nusra%20Front%20changed%20its%20name%20to%20Jabhat%20Fateh%20al-Sham%20(Front%20for%20the%20Conquest%20of%20Syria%2Fthe%20Levant)%20at%20the%20end%20of%20July%202016%2C%20reportedly%20cutting%20ties%20with%20al-Qaeda%20at%20the%20same%20time.%0AIt%20is%20thought%20that%20the%20public%20severing%20of%20links%20with%20al-Qaeda%20may%20not%20be%20as%20total%20as%20portrayed%2C%20and%20could%20be%20a%20means%20for%20the%20group%20to%20become%20involved%20in%20the%20political%20process%20in%20Syria%2C%20where%20it%20is%20fighting%20forces%20loyal%20to%20President%20Bashar%20al-Assad.%0ALed%20since%20its%20formation%20by%20Abu%20Mohammed%20al-Julani%2C%20Jabhat%20Fateh%20al-Sham%20(formerly%20known%20as%20Nusra%20Front)%20long%20tried%20to%20forge%20a%20broad%20alliance%20with%20other%20Syrian%20Islamist%20rebel%20groups%2C%20but%20its%20efforts%20had%20been%20hampered%20by%20its%20overt%20al-Qaeda%20links.%0AThe%20former%20Nusra%20Front%20was%20excluded%20from%20taking%20part%20in%20on-off%20US-%20and%20Russia-sponsored%20Syrian%20peace%20talks%20in%20Geneva%20and%20Vienna.%0ABaghdadi%27s%20creation%0AThe%20former%20Nusra%20front%20was%20formed%20at%20the%20end%20of%202011%2C%20the%20result%20of%20al-Qaeda%20in%20Iraq%27s%20leader%20(and%20now%20leader%20of%20so-called%20Islamic%20State%20(IS))%20Abu%20Bakr%20al-Baghdadi%20ordering%20Abu%20Muhammed%20al-Julani%20to%20organise%20jihadist%20groups%20in%20the%20region.%0A&ents=person%2Cnorp%2Corg%2Cgpe%2Cloc%2Cproduct%2Cdate%2Ctime&model=en) might be of use here.

**Comment by simonb83** [comment]
Yes, I am using Spacy to extract the named entities and then attempting to identify the relevant countries. I've done some more work on this, to include:

- Cities with population > 5000 (from www.geonames.org)
- Country subdivisions such as states, provinces, districts etc. (using pycountry)
- A couple of countries with common 'short' names that weren't mapping correctly to their official names

It will be interesting to see if we have any issues with spellings or utf-8 characters.

The current fail cases (based on 290 articles from article_contents.csv) are:
'Amur Oblast',
 'Balaghat',
 'Betul',
 'Bobonong',
 'Bodoland',
 'Burhanpur',
 'Daily News',
 'Dandane',
 'Gatore',
 'Gogrial East',
 'Haikota',
 'Harda',
 'Hashenkit',
 'Hulu Terengganu',
 'Karubaga Village',
 'Kirehe',
 'Luangphabang',
 'Mabumahibudu',
 'Matshekge',
 'Mayenrol',
 'Mekong River',
 'Mosweu',
 'Naitasiri',
 'Odisha',
 'Rasetimela',
 'Scribd',
 'Tolikara',
 'Viti Levu',
 'Warrap State'

**Comment by MrTones** [comment]
Would it be possible to use googlemaps api to find country?  Most of these work:
<code> https://maps.googleapis.com/maps/api/place/textsearch/json?query=Matshekge&key={ }</code>
Returns:
<code> "formatted_address" : "Bobonong, Botswana", </code>

**Comment by simonb83** [comment]
He @MrTones that's a nice idea. We could wrap a call to the API in a function, which we could then use if we cannot identify the country if the other methods fail.

**Comment by tmead24** [comment]
Yeah i was thinking you're current function should maybe keep something like a dictionary of places:country and then after scapy + dictionary if a noun isn't recognized make an Maps call last otherwise eventually with enough calls the project would have to start paying for the api.

**Comment by wwymak** [comment]
If you need a free api place lookup you can use Mapzen https://mapzen.com/products/search/
