### ISSUE TITLE
Visualization discussion

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#6]
The ultimate aim of this project is to make a visualization tool that can:
* Map the displacement figures and locations, identify hotspots and trends.
* Visualize reporting frequency and statistics for a selected region (using histogram or other such charts)
* Display excerpts of documents where the relevant information is reported (either by looking at the map or browsing the list of URLs).
* Visualize anything else you can think of!

To get started, datasets to play with can be found [here](https://milanoleonardo.carto.com/viz/64ee5010-d2a5-11e6-be93-0e3ff518bd15/public_map).

**Comment by georgerichardson** [comment]
Some refugee visualizations for inspiration:
- [Refugee Project](http://www.therefugeeproject.org/#/1975)
- [IDMC Carto Visualization](https://milanoleonardo.carto.com/viz/64ee5010-d2a5-11e6-be93-0e3ff518bd15/public_map)

Less directly related but still cool:
- [Charles Joseph Minard visualizing 6 types of data in 2 dimensions on Napoleonic campaign](https://en.m.wikipedia.org/wiki/Charles_Joseph_Minard#/media/File%3AMinard.png)
- [Visualizing Boston's Subway System](http://mbtaviz.github.io/)

**Comment by alemosie** [comment]
Non-interactive visualizations:

- [Perceived vs real size of Muslim population in France, U.S. and elsewhere](https://twitter.com/XtageLabs/status/810856072663666688?s=09)

**Comment by minedamnesia** [comment]
These each take a bit to load, but I also found these to be inspirational:

- https://www.lucify.com/the-flow-towards-europe/
- http://www.lucify.com/the-cost-of-displacement

**Comment by georgerichardson** [comment]
A cool way of visualising reports on maps (from @wwymak) 
- https://unfiltered.news/#/2017/02/26/es

**Comment by frenski** [comment]
This is the one from IOM (not the prettiest one, but people working in the field told me they find it very useful):
http://migration.iom.int/europe/

**Comment by frenski** [comment]
This is an interesting one too:
http://metrocosm.com/global-immigration-map/
