### ISSUE TITLE
Improve detection of numbers by spacy.

### ISSUE THREAD

**Issue by jlln** [Data4Democracy/internal-displacement#62]
The extraction of information from unstructured texts currently relies on the ability of spacy to identify number-like substrings within text. 
Specifically, the like_num method of the spacy Token class is used  [https://spacy.io/docs/api/token](https://spacy.io/docs/api/token).

This method fails to detect approximate numerical terms (eg hundreds, thousands, dozens, few). While these terms are approximate, they are still useful for establishing orders of magnitude, and when compared across reports.

If someone could create an improved method to determine if a spacy token is like a number, that would significantly improve our ability to extract information from texts.

More details on this issue are included in this notebook.
[https://github.com/Data4Democracy/internal-displacement/blob/master/notebooks/DependencyTreeExperiments3.ipynb](https://github.com/Data4Democracy/internal-displacement/blob/master/notebooks/DependencyTreeExperiments3.ipynb)

**Comment by Guilhermeslucas** [comment]
This sounds nice! I can try it. What script is doing this type of analysis right now?

**Comment by simonb83** [comment]
Hi @Guilhermeslucas, the function where we use this may look something like this:

```
def process_branch(token):
    children = [token] + get_all_descendent_tokens(token)
    reporting_unit, number = None, None
    for child in children:
        if child.like_num:
            number = child.text
        elif child.lemma_ in reporting_unit_lemmas:
            reporting_unit = child.text
    return reporting_unit, number
```

In particular, we iterate over a list of tokens parsed by Spacy, and for each one try and identify whether or not it is number-like (line 5) `if child.like_num`

Currently we are using the internal Spacy method above, `.like_num`....instead we could at this point make a call to a new function, say `like_number()` which could extend the Spacy method to also deal with the cases mentioned by @jlln above and detailed in the notebook that he references.

**Comment by jlln** [comment]
I agree with what Simon wrote. I think a new function:
 like_number(token)  => Boolean

that accepts a spacy token and returns a boolean is the way to go.

**Comment by Guilhermeslucas** [comment]
I'll try to it, so! Thanks for te help, guys!

**Comment by supersambo** [comment]
I'm not sure if this is of any help for how you are approaching this. But the spacy's named entity recognition seems to be doing a decently accurate job at identifying spelled numbers.

```
number_testing_string = ("Hundreds and thousands are a key ingredient in fairy bread, an Australian delicacy."
                         "I ate several slices at my birthday party and now I am hyperactive."
                         "Dozens of my guests are similiarly afflicted."
                         "A few parents have attempted to control the situation,"
                         "but their efforts have thus far ended in failure."
                         "Today I am turning three years old. There are 19 guests at the party."
                         )
number_test_model = nlp(number_testing_string)

for entity in number_test_model.ents:
    if entity.label_ == "CARDINAL":
        print(entity)
```

output is 

```
Hundreds and thousands
Dozens
19
```
Obviously "Hundreds and thousands" is a pretty tough one but "Hundreds of thousands" should be recognizable. Btw. "three years old" is classified as DATE.

**Comment by simonb83** [comment]
Thanks @supersambo. Yes we are using Spacy's entity recognition and in general it works pretty well, however there are some cases that it doesn't pick up, probably due to unusual context or phrasing.
Unfortunately I don't have any examples off the top of my head. Probably the best thing is to park this for the time being until we have a better list of fail cases and then we can figure out whether we need to re-train the spacy model or use some other approach.
