### ISSUE TITLE
Database schema for documents

### ISSUE THREAD

**Issue by WanderingStar** [Data4Democracy/internal-displacement#73]
Need an initial DB schema to capture information about documents and facts.

Proposal:
Tables:
- Article (id, URL, retrieval date, source, publication date, title, authors, language, analyzer, analysis date) -- metadata extracted from a retrieved article
- Full Text (article, content) full text of article
- Analysis (id, article, reason, location, reporting term, reporting unit, number, metrics, analyzer analysis date) -- analysis of retrieved article

**Comment by georgerichardson** [comment]
The tables look good to me. Do you want to know every possible column that we might have for each of them? I can think of a few more.

**Comment by WanderingStar** [comment]
Yes, please.
