### ISSUE TITLE
Create Dockerfile for internal-displacement

### ISSUE THREAD

**Issue by WanderingStar** [Data4Democracy/internal-displacement#78]
Should encapsulate all of the dependencies.

**Comment by WanderingStar** [comment]
I *think* that installing textract per https://textract.readthedocs.io/en/stable/installation.html
And `pip install -r requirements.txt` should be sufficient, with the additions to requirements in #77

**Comment by georgerichardson** [comment]
Just a heads up that our `requirements.txt` might not include imminent additions from the Jupyter notebooks
