### ISSUE TITLE
Get random subsample of URLs from list

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#8]
There is a placeholder function `sample_urls` in `scrape_articles.py`. This should be updated to return a random subsample URLs in a list.

**Comment by simonb83** [comment]
Happy to kick things off with this one...just wanted to clarify the expected behaviour. I notice the placeholder has index and sample parameters.
I imagine that the sample is the sample size?
What is the idea behind the index param?

**Comment by georgerichardson** [comment]
Cool! I can't say that I put that in there with too much forethought. I think the idea was to allow you to take a slice of the list using a range specified in `index` and to specify whether you wanted a random sample using True/False for `sample`. That doesn't seem like the best though (and might not even be what I originally intended...), so feel free to redesign as you see fit.

One thing that would be handy is the ability to choose a sample size by specifying an integer number of samples or a decimal to represent a percentage.

**Comment by simonb83** [comment]
Got it. I'll start on this if you want to assign it to me.

**Comment by simonb83** [comment]
Just realized that the `scrape_articles.py` file is misnamed and is currently called `scrape_artlces.py`. Do you want me to correct the name as part of this issue?

**Comment by georgerichardson** [comment]
Yeah. I actually don't think that's even the appropriate file name anymore, so change it to something else that you feel might be better
