### ISSUE TITLE
Articles to reports

### ISSUE THREAD

**Issue by georgerichardson** [Data4Democracy/internal-displacement#96]
Given an `Article`, if it is in English, make a call to `Interpreter.process_article_new` to obtain the `Reports`; for each `Report` returned, save in Report table; if no `Reports`, then set its relevance to be `False`

**Comment by domingohui** [comment]
I'd love to take a crack at this! Would I base my changes on @simonb83's [interpreter](https://github.com/Data4Democracy/internal-displacement/tree/interpreter) branch?

**Comment by simonb83** [comment]
Hi @domingohui that would be great.

Yes it would be best to work in the Interpreter branch as that is where the most up-to-date NLP functions are.

The function itself should probably go somewhere in `pipeline.py` and make calls to the Interpreter, Article, Report classes etc as appropriate.

**Comment by domingohui** [comment]
Please take a look at #101. I will keep pushing as I learn more about the whole pipeline process.

**Comment by simonb83** [comment]
This is probably covered by #107
